
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package be.vsop.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TYPE_IDENTIFIER = 40;
  public static final int POW = 32;
  public static final int STRING_LITERAL = 38;
  public static final int UMINUS = 42;
  public static final int INT32 = 11;
  public static final int UNIT = 19;
  public static final int LOWER = 35;
  public static final int MINUS = 29;
  public static final int NOT = 15;
  public static final int SEMICOLON = 26;
  public static final int AND = 2;
  public static final int RPAR = 24;
  public static final int IN = 10;
  public static final int BOOL = 3;
  public static final int COMMA = 27;
  public static final int CLASS = 4;
  public static final int DIV = 31;
  public static final int PLUS = 28;
  public static final int ASSIGN = 37;
  public static final int IF = 9;
  public static final int DOT = 33;
  public static final int EOF = 0;
  public static final int EQUAL = 34;
  public static final int TRUE = 18;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int ISNULL = 12;
  public static final int TIMES = 30;
  public static final int COLON = 25;
  public static final int LBRACE = 21;
  public static final int ELSE = 6;
  public static final int WHILE = 20;
  public static final int LET = 13;
  public static final int THEN = 17;
  public static final int RBRACE = 22;
  public static final int LOWER_EQUAL = 36;
  public static final int EXTENDS = 7;
  public static final int LPAR = 23;
  public static final int STRING = 16;
  public static final int FALSE = 8;
  public static final int DO = 5;
  public static final int INT_LITERAL = 41;
  public static final int IDENTIFIER = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "BOOL",
  "CLASS",
  "DO",
  "ELSE",
  "EXTENDS",
  "FALSE",
  "IF",
  "IN",
  "INT32",
  "ISNULL",
  "LET",
  "NEW",
  "NOT",
  "STRING",
  "THEN",
  "TRUE",
  "UNIT",
  "WHILE",
  "LBRACE",
  "RBRACE",
  "LPAR",
  "RPAR",
  "COLON",
  "SEMICOLON",
  "COMMA",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "POW",
  "DOT",
  "EQUAL",
  "LOWER",
  "LOWER_EQUAL",
  "ASSIGN",
  "STRING_LITERAL",
  "IDENTIFIER",
  "TYPE_IDENTIFIER",
  "INT_LITERAL",
  "UMINUS"
  };
}

