
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TYPE_IDENTIFIER = 43;
  public static final int POW = 35;
  public static final int STRING_LITERAL = 41;
  public static final int UMINUS = 2;
  public static final int INT32 = 14;
  public static final int UNIT = 22;
  public static final int IDENTIDIER = 42;
  public static final int LOWER = 38;
  public static final int LPAREN = 3;
  public static final int MINUS = 32;
  public static final int RPAREN = 4;
  public static final int NOT = 18;
  public static final int SEMICOLON = 29;
  public static final int AND = 5;
  public static final int RPAR = 27;
  public static final int IN = 13;
  public static final int BOOL = 6;
  public static final int COMMA = 30;
  public static final int CLASS = 7;
  public static final int DIV = 34;
  public static final int PLUS = 31;
  public static final int ASSIGN = 40;
  public static final int IF = 12;
  public static final int DOT = 36;
  public static final int EOF = 0;
  public static final int EQUAL = 37;
  public static final int TRUE = 21;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int ISNULL = 15;
  public static final int TIMES = 33;
  public static final int COLON = 28;
  public static final int LBRACE = 24;
  public static final int ELSE = 9;
  public static final int WHILE = 23;
  public static final int LET = 16;
  public static final int THEN = 20;
  public static final int RBRACE = 25;
  public static final int LOWER_EQUAL = 39;
  public static final int EXTENDS = 10;
  public static final int LPAR = 26;
  public static final int STRING = 19;
  public static final int FALSE = 11;
  public static final int DO = 8;
  public static final int INT_LITERAL = 44;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "UMINUS",
  "LPAREN",
  "RPAREN",
  "AND",
  "BOOL",
  "CLASS",
  "DO",
  "ELSE",
  "EXTENDS",
  "FALSE",
  "IF",
  "IN",
  "INT32",
  "ISNULL",
  "LET",
  "NEW",
  "NOT",
  "STRING",
  "THEN",
  "TRUE",
  "UNIT",
  "WHILE",
  "LBRACE",
  "RBRACE",
  "LPAR",
  "RPAR",
  "COLON",
  "SEMICOLON",
  "COMMA",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "POW",
  "DOT",
  "EQUAL",
  "LOWER",
  "LOWER_EQUAL",
  "ASSIGN",
  "STRING_LITERAL",
  "IDENTIDIER",
  "TYPE_IDENTIFIER",
  "INT_LITERAL"
  };
}

